wallpaper {
    monitor = DP-3
    path = ~/myFile.jxl
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/myFile2.jxl
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = /home/mc/marc/pictures/wallpaper
    fit_mode = cover
    timeout = 300
    order = random
}

splash = false
splash_offset = 50
splash_opacity = 50

